Folder: VTS PERF AND SCALE
Title: no CSR, 1 PVVP chain with 1k flows
Description: runs number of perfomance benchmarks described in https://cisco.jiveon.com/docs/DOC-1711443. Target architecture is defined by pod on which this test is run.
UniqueID: os-sqe-perf05

Workers:

- class: lab.scenarios.ntt_scenario.NttScenario
  name: NttScenario
  delay: 0
  timeout: 1000
  pause: 0
  run: 1
  run_inside: nfvbench
  csr_args: not-used
  nfvbench_args: --rate ndr_pdr --service-chain PVVP --service-chain-count 1 --inter-node --flow-count 1000 --frame-size 64 --frame-size IMIX --frame-size 1518
